build:
   #! /usr/bin/bash
   start=$(date +%s) 
   echo "building..."             
   rustc numeric-types.rs 
   end=$(date +%s) 
   echo -e "Time elapsed: $((($end - $start) / 1000000))s\n" 

run: build
   @echo "running numeric types..."
   @./numeric-types

clean:
   @echo "cleaning..."
   rm numeric-types


